let words = ['AAHINGAALIISAARRGHAARTIS' , 'ABACAS', 'ABACUS', 'ABAKADAME','DAMMDAMNDAMP','DAMP','DANC','DAND','DANG','DANI','DANKDANN','DANT','DARADARB',
'DARC','DARE','DARE','DARE','DARG','DARG','DARIDARI','DARK','DARKDARN','ABAMPS', 'ABANDS', 'ABASED', 'ABASERABASES', 'ABASIA', 'ABATED', 'ABATER', 'ABATES', 'ABATIS', 'ABATOR', 'ABATTU'];
words = words.map(function(string){return string.toLowerCase();})
